import time
import random


def predict_conversion(ad_text: str) -> dict:
    """
    MOCK ML FUNCTION: Simulates a heavy PyTorch model inference task.
    DO NOT edit this file. Your goal is to serve this function via an API.

    Raises:
        ValueError: If the input text is too short for analysis.
        RuntimeError: If the mock model fails to load.
    """
    # Simulate loading the model into memory / GPU transfer
    time.sleep(random.uniform(2.0, 4.0))

    if not ad_text or len(ad_text) < 10:
        raise ValueError("Input text must be at least 10 characters for analysis.")

    # Deterministic failure path for testing
    if "force_runtime_error" in ad_text.lower():
        raise RuntimeError(
            "Model inference failed: internal scoring engine returned a null result."
        )

    return {
        "impulse_score": round(random.uniform(0.5, 0.99), 2),
        "trust_score": round(random.uniform(0.1, 0.8), 2),
        "conversion_probability": round(random.uniform(0.3, 0.85), 2),
        "model_version": "v1.0-mock",
    }